stages:
  - build

pages:
  stage: build
  image: node:latest
  variables:
    GIT_STRATEGY: clone
    VUE_APP_CACHE_ID: $CI_COMMIT_SHA
  before_script:
    - yarn install

  script:
    - yarn test:unit
    - yarn build
    - rm -rf public
    - mv dist public
  cache:
    key: front_node_modules
    paths:
      - "node_modules"
  artifacts:
    paths:
      - public/
  only:
    - master
  tags:
    - docker
